variable "aws_region" {
  description = "The aws region (us-east-1, us-east-2, etc.) this is being hosted in."
}

variable "domain" {
  description = "The top level domain name."
  default     = "example.com"
}

variable "project_name" {
  description = "The name of the project, gets passed in to naming and tagging a lot of the resources."
}

variable "proxied_services" {
  description = "Services to reverse-proxy from the EC2 Caddy instance to the home media server, each getting its own hostname (subdomain.domain), Route53 A record, and Let's Encrypt cert. Add an entry here instead of a new variable to expose another service."
  type = list(object({
    name      = string
    subdomain = string
    port      = number
  }))
}

variable "ubuntu_ami_id" {
  description = "The Ubuntu AMI ID to be used. Should be latest Ubuntu in the designated region."
}

variable "wg_ec2_ip" {
  description = "The WireGuard Interface Address on the EC2 instance."
  default     = "10.10.0.1"
}

variable "wg_ec2_private_key" {
  description = "The EC2 side's real WireGuard private key, pulled from the already-running instance's /etc/wireguard/wg0.conf - not generated by Tofu, since a freshly-generated one wouldn't match the live tunnel."
  sensitive   = true
  default     = null
}

variable "wg_media_sever_ip" {
  description = "The WireGuard Interface Address on the media server."
  default     = "10.10.0.2"
}

variable "zone_id" {
  description = "The Route53 ZoneID."
}
